version: "3"

services:
  xnode-consensus0:
    container_name: xnode-consensus0
    image: "tendermint-app"
    ports:
      - "8088"
      - "26656-26657:26656-26657"
    volumes:
      - ./cometbft/build:/cometbft:Z
    environment:
      - ID=0
      - LOG=${LOG:-cometbft.log}
    build:
      context: .
      dockerfile: ../xnode-app/Dockerfile
    command: /tendermint-app --cmt-home=/cometbft/node0
    networks:
      localnet:
        ipv4_address: 192.166.10.2

  xnode-consensus1:
    container_name: xnode-consensus1
    image: "tendermint-app"
    ports:
      - "8088"
      - "26659-26660:26656-26657"
    volumes:
      - ./cometbft/build:/cometbft:Z
    environment:
      - ID=1
      - LOG=${LOG:-cometbft.log}
    build:
      context: .
      dockerfile: ../xnode-app/Dockerfile
    command: /tendermint-app --cmt-home=/cometbft/node1
    networks:
      localnet:
        ipv4_address: 192.166.10.3

  xnode-consensus2:
    container_name: xnode-consensus2
    image: "tendermint-app"
    ports:
      - "8088"
      - "26661-26662:26656-26657"
    volumes:
      - ./cometbft/build:/cometbft:Z
    environment:
      - ID=2
      - LOG=${LOG:-cometbft.log}
    build:
      context: .
      dockerfile: ../xnode-app/Dockerfile
    command: /tendermint-app --cmt-home=/cometbft/node2
    networks:
      localnet:
        ipv4_address: 192.166.10.4

  xnode-consensus3:
    container_name: xnode-consensus3
    image: "tendermint-app"
    ports:
      - "8088"
      - "26663-26664:26656-26657"
    volumes:
      - ./cometbft/build:/cometbft:Z
    environment:
      - ID=3
      - LOG=${LOG:-cometbft.log}
    build:
      context: .
      dockerfile: ../xnode-app/Dockerfile
    command: /tendermint-app --cmt-home=/cometbft/node3
    networks:
      localnet:
        ipv4_address: 192.166.10.5

  xnode-data0:
    container_name: xnode-data0
    image: "xnode"
    build:
      context: .
      dockerfile: ../data-mock/Dockerfile
    command: data-provider.js 192.166.10.2 # xnode-consensus0
    networks:
      localnet:
        ipv4_address: 192.166.10.6

  xnode-data1:
    container_name: xnode-data1
    image: "xnode"
    build:
      context: .
      dockerfile: ../data-mock/Dockerfile
    command: data-provider.js 192.166.10.3 # xnode-consensus1
    networks:
      localnet:
        ipv4_address: 192.166.10.7

  xnode-data2:
    container_name: xnode-data2
    image: "xnode"
    build:
      context: .
      dockerfile: ../data-mock/Dockerfile
    command: data-provider.js 192.166.10.4 # xnode-consensus2
    networks:
      localnet:
        ipv4_address: 192.166.10.8

  xnode-data3:
    container_name: xnode-data3
    image: "xnode"
    build:
      context: .
      dockerfile: ../data-mock/Dockerfile
    command: data-provider.js 192.166.10.5 # xnode-consensus3
    networks:
      localnet:
        ipv4_address: 192.166.10.9

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.166.10.0/16
